### ISSUE TITLE
[BUG] - Some methods are returning "400 – Request contains an invalid argument"

### ISSUE THREAD

**Issue by jtbergman** [b5i/YouTubeKit#28] opened 2024-09-20 03:45 UTC
**Describe the bug**
Hi, thanks for the project. I noticed that some methods are returning "400 – Requests contains an invalid argument". I tried both the framework in my own app and within the Atwy app. The two requests I've seen returning this so far are `SearchResponse` and `PlaylistInfosResponse`

**To Reproduce**
This is reproducible on the home tan of Atwy and within the test code for playlists:
```swift
let playlist = YTPlaylist(playlistId: "VLPLw-VjHDlEOgs658kAHR_LAaILBXb-s6Q5")
let response = try await playlist.fetchVideosThrowing(youtubeModel: model)
```

I tried these both with and without cookies set.

**Expected behavior**
Perhaps the requests need to be updated, I expect them to not 404.

**Additional context**
<img width="879" alt="image" src="https://github.com/user-attachments/assets/52625719-f010-4b22-97d4-d8fee9b935e5">

**Comment by b5i** [comment] 2024-09-20 06:12
Hello! Thanks for your detailed bug report. Unfortunately, I can’t reproduce the bug on my side. I realized there was a bug in the playlists extraction and it’s now fixed (in YouTubeKit and Atwy), that might have been the cause of the issue in your case, but it shouldn’t return a 404/400 error.
To debug I’d need you to activate the logger in Atwy’s settings. Then reproduce the bugs and upload every concerned log (zip) in this channel so I can try to understand what the problem was.
Also, could you try to 
- navigate to this [URL](https://www.youtube.com/playlist?list=PLw-VjHDlEOgs658kAHR_LAaILBXb-s6Q5) which is the playlist of the tests that you used to reproduce the error. It might be because your location is forbidden to access the content;
- run YouTubeKit’s tests to see if they all pass?

Thank you

**Comment by b5i** [comment] 2024-11-19 15:45
Any update on this issue?

**Closed** 2024-11-30 18:45 UTC
Labels: bug
